appname: "Metshe::Web"
layout: "main"
charset: "UTF-8"
template: "template_toolkit"
engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '[%'
    end_tag:   '%]'

model:
  connect_info:
    - 'dbi:mysql:metshe:localhost'
    - ''
    - ''
    - RaiseError: 1
      AutoCommit: 1
      mysql_enable_utf8: 1
      on_connect_do:
        - "SET NAMES utf8"

