CREATE TABLE user (
  id        INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email     VARCHAR(255) NOT NULL,
  passwd    VARCHAR(255) NOT NULL,
  birthday  DATE NOT NULL,
  gender    INT NOT NULL,
  created_on  DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  updated_on  DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00'
) ENGINE=InnoDB;

CREATE TABLE bbs (
  id         INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  bbs_id     VARCHAR(32) NOT NULL,
  user_id    INT NOT NULL,
  comment    TEXT NOT NULL,
  reply_id   INT NOT NULL DEFAULT 0,
  created_on DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  updated_on DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00'
) ENGINE=InnoDB;

